analyzer:
  errors:
    unused_import: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unused_element: ignore
    deprecated_member_use: ignore
    dead_null_aware_expression: ignore
    unnecessary_null_comparison: ignore
    invalid_dependency: ignore
    depend_on_referenced_packages: ignore
    duplicate_import: ignore
    unnecessary_import: ignore
    avoid_print: ignore
    avoid_renaming_method_parameters: ignore
    prefer_final_fields: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    use_super_parameters: ignore
    unnecessary_non_null_assertion: ignore
    invalid_use_of_visible_for_testing_member: ignore
    invalid_use_of_protected_member: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_interpolation_to_compose_strings: ignore
    use_build_context_synchronously: ignore
    unnecessary_const: ignore
    implementation_imports: ignore
    unnecessary_brace_in_string_interps: ignore
    await_only_futures: ignore
    unrelated_type_equality_checks: ignore
    include_file_not_found: ignore

linter:
  rules: